Demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("POS/",include("Food_POS.urls")),
    path("emr/",include("emr.urls")),
]

emr/urls.py
from django.urls import path

from .views import lead_status_views, lead_source_views

app_name = "emr"

urlpatterns = [
    path('leadstatus/', lead_status_views.LeadStatusListView.as_view(), name="leadstatus_list"),
    path('leadstatus/create/', lead_status_views.CreateLeadStatus.as_view(), name="leadstatus_create"),
    path('leadstatus/update/<int:pk>/', lead_status_views.UpdateLeadStatus.as_view(), name="leadstatus_update"),
    path('leadstatus/delete/<int:pk>/', lead_status_views.DeleteLeadStatus.as_view(), name="leadstatus_delete"),

    path('leadsource/', lead_source_views.LeadSourceListView.as_view(), name="leadsource_list"),
    path('leadsource/create/', lead_source_views.CreateLeadSource.as_view(), name="leadsource_create"),
    path('leadsource/update/<int:pk>/', lead_source_views.UpdateLeadSource.as_view(), name="leadsource_update"),
    path('leadsource/delete/<int:pk>/', lead_source_views.DeleteLeadSource.as_view(), name="leadsource_delete"),
]

emr/models/billing.py
import uuid
from django.db import models

from emr.models.business import Facility
from emr.models.patient import Visit

class CareLevel(models.Model):
    id = models.UUIDField(default=uuid.uuid4())
    facility = models.ForeignKey(Facility,on_delete=models.CASCADE,related_name="care_levels")
    name = models.CharField(max_length=30)
    charge_amount = models.DecimalField(max_digits=10,decimal_places=2)
    admission_date_charge = models.BooleanField(default=True)
    discharge_date_charge = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
class Claim(models.Model):
    id = models.UUIDField(default=uuid.uuid4())
    admission = models.ForeignKey(Visit,null=True,blank=True)
    service_date = models.DateField()
    charge_amount = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    


    

emr/models/business.py
import uuid
from django.db import models


class Entity(models.Model):
    id = models.UUIDField(default=uuid.uuid4(),primary_key=True)
    name = models.CharField(max_length=70)

    def __str__(self):
        return self.name

class Facility(models.Model):
    id = models.UUIDField(default=uuid.uuid4(),primary_key=True)
    entity = models.ForeignKey(Entity,on_delete=models.CASCADE,related_name="facilities")
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

emr/models/crm.py
from django.db import models
import uuid

from emr.models.generic import Person

class LeadStatus(models.Model):
    name = models.CharField(max_length=100,unique=True)
    created_on = models.DateField(auto_now_add=True,editable=False)
    modified_on = models.DateField(auto_now=True,editable=False)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class LeadSource(models.Model):
    name = models.CharField(max_length=100,unique=True)

    def __str__(self):
        return self.name
    
class OpportunityStage(models.Model):
    name = models.CharField(max_length=100,unique=True)

    def __str__(self):
        return self.name

class Company(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    # Add more fields as necessary

    def __str__(self):
        return self.name


class Lead(models.Model):
    id = models.UUIDField(default=uuid.uuid4(),primary_key=True)
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True, blank=True)

    status = models.ForeignKey(LeadStatus,on_delete=models.SET_NULL,null=True,related_name="leads")
    source = models.ForeignKey(LeadSource,on_delete=models.SET_NULL,null=True,related_name="leads")
    notes = models.TextField(blank=True, null=True)
    # Other lead-specific fields...

    def __str__(self):
        return f"{self.person.first_name} {self.person.last_name}"


class Opportunity(models.Model):
    lead = models.ForeignKey(Lead, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    stage = models.ForeignKey(OpportunityStage,on_delete=models.SET_NULL,null=True,related_name="opportunities")
    close_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

emr/models/generic.py
from django.db import models
import uuid

class Person(models.Model):
    #This will contain all of the Hippa info so to not leak information
    id = models.UUIDField(default=uuid.uuid4(),primary_key=True)
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField()

    def __str__(self):
        return self.name
    
    def full_name(self):
        return f"{self.first_name} {self.middle_name} {self.last_name}".replace("  "," ").strip()
    
    def name(self):
        return f"{self.first_name} {self.last_name}"

emr/models/patient.py
import uuid
from django.db import models

from emr.models.generic import Person
from emr.models.business import Facility
from emr.models.billing import CareLevel

class Visit(models.Model):
    id = models.UUIDField(default=uuid.uuid4(),primary_key=True)
    person = models.ForeignKey(Person,on_delete=models.CASCADE,related_name='admissions')
    facility = models.ForeignKey(Facility,on_delete=models.CASCADE,related_name='admissions')
    admission_date = models.DateTimeField()
    discharge_date = models.DateTimeField(null=True)
    diagnosis = models.JSONField(default=[])

    def __str__(self):
        return self.id
    
class LevelOfCare(models.Model):
    id = models.UUIDField(default=uuid.uuid4(),primary_key=True)
    service = models.ForeignKey(CareLevel,on_delete=models.CASCADE,related_name="locs")
    visit = models.ForeignKey(Visit,on_delete=models.CASCADE,related_name="locs")
    start_date = models.DateField()
    end_date = models.DateField(null=True)

class Authorization(models.Model):
    id = models.UUIDField(default=uuid.uuid4(),primary_key=True)
    visit = models.ForeignKey(Visit,on_delete=models.CASCADE,related_name="authorizations")
    authorization_code = models.CharField(max_length=200)
    units = models.IntegerField()
    start_date = models.DateField()
    end_date = models.DateField(null=True)

    

emr/models/seed.py
from emr.models.crm import OpportunityStage, LeadSource, LeadStatus


def default_setup():
    default_opportunity_stages = ["Prospecting","Qualification","Proposal","Negotiation","Closed Won","Closed Lost"]
    OpportunityStage.objects.all().delete()
    for stage in default_opportunity_stages:
        obj = OpportunityStage.objects.create(name=stage)
        obj.save()

    default_lead_status = ["New","Contacted","Qualified","Converted","Unqualified"]
    LeadStatus.objects.all().delete()
    for status in default_lead_status:
        obj = LeadStatus.objects.create(name=status)
        obj.save()

    default_lead_sources = ["Referral","Website","Social Media","Email Campaign","Event","Advertising","Cold Call","Partnerships","Direct Mail"]
    for source in default_lead_sources:
        obj = LeadSource.objects.create(name=source)
        obj.save()

emr/forms/lead_forms.py
from django.forms import ModelForm

from emr.models.crm import LeadStatus, LeadSource, Lead

class LeadStatusCreateForm(ModelForm):
    class Meta:
        model = LeadStatus
        fields = "__all__"

emr/views/lead_source_views.py
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404
from emr.models.crm import LeadSource

class LeadSourceListView(ListView):
    model = LeadSource
    template_name = 'leadsource_list.html'
    context_object_name = 'lead_statuses'

    def get_template_names(self):
        if self.request.htmx:
            return ["partials/leadsource_list_partial.html"]
        return ["leadsource_list.html"]

class CreateLeadSource(CreateView):
    model = LeadSource
    template_name = 'partials/leadsource_form.html'
    success_url = reverse_lazy("emr:leadsource_list")
    fields = "__all__"

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.htmx:
            return render(self.request, "partials/leadsource_list_partial.html", {"object_list": self.model.objects.all()})
        return response

class UpdateLeadSource(UpdateView):
    model = LeadSource
    template_name = 'partials/leadsource_form.html'
    success_url = reverse_lazy("emr:leadsource_list")
    fields = "__all__"

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.htmx:
            return render(self.request, "partials/leadsource_list_partial.html", {"object_list": self.model.objects.all()})
        return response

class DeleteLeadSource(DeleteView):
    model = LeadSource
    template_name = 'partials/leadsource_confirm_delete.html'
    success_url = reverse_lazy("emr:leadsource_list")

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        if self.request.htmx:
            return render(self.request, "partials/leadsource_list_partial.html", {"object_list": self.model.objects.all()})
        return response

emr/views/lead_status_views.py
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404
from emr.models.crm import LeadStatus

class LeadStatusListView(ListView):
    model = LeadStatus
    template_name = 'leadstatus_list.html'
    context_object_name = 'lead_statuses'

    def get_template_names(self):
        if self.request.htmx:
            return ["partials/leadstatus_list_partial.html"]
        return ["leadstatus_list.html"]

class CreateLeadStatus(CreateView):
    model = LeadStatus
    template_name = 'partials/leadstatus_form.html'
    success_url = reverse_lazy("emr:leadstatus_list")
    fields = "__all__"

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.htmx:
            return render(self.request, "partials/leadstatus_list_partial.html", {"object_list": self.model.objects.all()})
        return response

class UpdateLeadStatus(UpdateView):
    model = LeadStatus
    template_name = 'partials/leadstatus_form.html'
    success_url = reverse_lazy("emr:leadstatus_list")
    fields = "__all__"

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.htmx:
            return render(self.request, "partials/leadstatus_list_partial.html", {"object_list": self.model.objects.all()})
        return response

class DeleteLeadStatus(DeleteView):
    model = LeadStatus
    template_name = 'partials/leadstatus_confirm_delete.html'
    success_url = reverse_lazy("emr:leadstatus_list")

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        if self.request.htmx:
            return render(self.request, "partials/leadstatus_list_partial.html", {"object_list": self.model.objects.all()})
        return response

emr/templates/partials/leadsource_confirm_delete.html
<div class="modal-content">
    <div class="modal-title" style="text-align: center;">
        <h3>
            Delete Lead Source Label "{{ object.name }}"
        </h3>
    </div>
    <form method="post" class="modal-content" hx-post="{% url 'emr:leadstatus_delete' object.pk %}" hx-target="#leadstatus-list" hx-swap="innerHTML" hx-include="[name=csrfmiddlewaretoken]" hx-on="htmx:afterRequest:#leadstatus-modal:hide.bs.modal">
        {% csrf_token %}
        <input type="hidden" name="_method" value="DELETE">
        <div class="modal-body">
            <p>Are you sure you want to delete lead status label with the name of "{{ object.name }}"?  Doing so will set all Lead statuses to Null that use this status name.</p>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-danger">Delete</button>
            <button type="button" class="btn btn-secondary close-modal-btn">Close</button>
        </div>
    </form>
</div>

emr/templates/partials/leadsource_form.html
<div class="modal-content">
    <div class="modal-title" style="text-align: center;">
      <h3>
      {% if object.pk %} Edit Existing Lead Status Label {% else %} Create New Lead
      Status Label {% endif %}
      </h3>
    </div>
    <hr class="hr" />
    <form
      method="post"
      hx-post="{% if object.pk %}{% url 'emr:leadstatus_update' object.pk %}{% else %}{% url 'emr:leadstatus_create' %}{% endif %}"
      hx-target="#leadstatus-list"
      hx-swap="innerHTML"
      hx-on="htmx:afterRequest:#leadstatus-modal:hide.bs.modal"
      style="text-align: center;"
    >
      {% csrf_token %} {{ form.as_p }}
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-secondary close-modal-btn">
          Close
        </button>
      </div>
    </form>
  </div>
  

emr/templates/partials/leadsource_list_partial.html
<table class="table table-striped">
    <thead>
        <tr>
            <th>Label</th>
            <th>Created On</th>
            <th>Modifed On</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <td>{{ object.name }}</td>
            <td>{{ object.created_on }}</td>
            <td>{{ object.modified_on }}</td>
            <td>{{ object.active }}</td>
            <td>
                <button class="btn btn-warning btn-sm" hx-get="{% url 'emr:leadstatus_update' object.id %}" hx-target="#target-dialog" hx-trigger="click">Edit</button>
                <button class="btn btn-danger btn-sm" hx-get="{% url 'emr:leadstatus_delete' object.id %}" hx-target="#target-dialog" hx-trigger="click">Delete</button>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">No lead statuses found.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

emr/templates/partials/leadstatus_confirm_delete.html
<form method="post" class="modal-content" hx-post="{% url 'emr:leadstatus_delete' object.pk %}" hx-target="#leadstatus-list" hx-swap="innerHTML" hx-include="[name=csrfmiddlewaretoken]" hx-on="htmx:afterRequest:#leadstatus-modal:hide.bs.modal">
    {% csrf_token %}
    <input type="hidden" name="_method" value="DELETE">
    <div class="modal-body">
        <p>Are you sure you want to delete this lead status?</p>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-danger">Delete</button>
        <button type="button" class="btn btn-secondary close-modal-btn">Close</button>
    </div>
</form>

emr/templates/partials/leadstatus_form.html
<div class="modal-content">
  <div class="modal-title" style="text-align: center;">
    <h3>
    {% if object.pk %} Edit Existing Lead Status Label {% else %} Create New Lead
    Status Label {% endif %}
    </h3>
  </div>
  <hr class="hr" />
  <form
    method="post"
    hx-post="{% if object.pk %}{% url 'emr:leadstatus_update' object.pk %}{% else %}{% url 'emr:leadstatus_create' %}{% endif %}"
    hx-target="#leadstatus-list"
    hx-swap="innerHTML"
    hx-on="htmx:afterRequest:#leadstatus-modal:hide.bs.modal"
    style="text-align: center;"
  >
    {% csrf_token %} {{ form.as_p }}
    <div class="modal-footer">
      <button type="submit" class="btn btn-primary">Save</button>
      <button type="button" class="btn btn-secondary close-modal-btn">
        Close
      </button>
    </div>
  </form>
</div>

emr/templates/partials/leadstatus_list_partial.html
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Created On</th>
            <th>Modifed On</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <td>{{ object.name }}</td>
            <td>{{ object.created_on }}</td>
            <td>{{ object.modified_on }}</td>
            <td>{{ object.active }}</td>
            <td>
                <button class="btn btn-warning btn-sm" hx-get="{% url 'emr:leadstatus_update' object.id %}" hx-target="#target-dialog" hx-trigger="click">Edit</button>
                <button class="btn btn-danger btn-sm" hx-get="{% url 'emr:leadstatus_delete' object.id %}" hx-target="#target-dialog" hx-trigger="click">Delete</button>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">No lead statuses found.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>